### ISSUE TITLE
Postfix in follow up question conflicts with follow up question styling

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/honeycrisp-gem#144]
![Screen Shot 2019-12-04 at 2 28 14 PM](https://user-images.githubusercontent.com/451510/70187271-9cd5ed00-16a2-11ea-9869-44edbf10b525.png)

**Comment by bengolder** [comment]
We used this css to resolve the breakage. It looked like post-fix only text groups are lacking padding on the left.

```css
.question-with-follow-up__follow-up {
  .text-input-group__prefix {
    background-color: white;
  }

  .text-input-group__postfix {
    background-color: white;
  }
}

.text-input-group {
  .text-input:first-child {
    padding-left: 2.5rem;
  }
}
```
